### ISSUE TITLE
Question: Custom page

### ISSUE THREAD

**Issue by Norwayman** [septor/anteup#42]
I want to put a link in the menu that takes me to a page where I explain more about the spesific donation project. I want to include pictures and text about the project. How can I easily put the same text that I have in my menu (included the button and all) on my custom made page?

![menuscreenshot01](https://cloud.githubusercontent.com/assets/1757346/21914788/18518fcc-d8fb-11e6-8d7b-eae685314cc8.JPG)

**Comment by septor** [comment]
Easiest way is for the shortcodes to be usable side wide. Tagging this for 1.2.0 for now.

**Comment by Moc** [comment]
This has now been done. 
Very important: you need to run the "Tools > Database > Scan plugin directories for changes" functionality. Otherwise the shortcodes will not work at all. 

I'll still have to include a check for this when updating to the next release, so I am keeping this issue open. 

@Norwayman You can do this manually already, as the next release will still take time. Update using the files from Github and then run the scan for changes functionality as described above.

**Comment by septor** [comment]
I just pushed some changes that should handle those issues.

**Comment by Moc** [comment]
I'll do an upgrade test to ensure this works. After that I'll close this issue.
